# SyncAI-ROS2-Rust - common commands
#
#   make image     build the Docker image (required once, takes about 10-20 minutes)
#   make up        start the container
#   make interface pull the shared syncai_common messages into src/ (run once after cloning)
#   make build     build the workspace with colcon inside the container
#   make fmt       format every Rust package with rustfmt
#   make fmt-check check formatting without changing files (for CI)
#   make lint      run clippy on every Rust package (needs one make build first)
#   make shell     open an interactive shell in the container
#   make down      stop and remove the container
#   make clean     remove build output

COMPOSE := docker compose
SERVICE := ros2-rust
EXEC    := $(COMPOSE) exec $(SERVICE)

.PHONY: image up down shell interface interface-update build fmt fmt-check lint echo topics clean distclean

image:
	$(COMPOSE) build

up:
	$(COMPOSE) up -d

down:
	$(COMPOSE) down

shell: up
	$(EXEC) bash

# Shared message package syncai_common (SyncAI-Robot-Interface); see interface.repos.
# Uses the vcstool inside the container, so nothing extra is needed on the host. interface.repos
# is fed in over stdin so this works whatever the container mounts (exec -T avoids allocating a
# TTY so the pipe works).
# Writing to /workspace/src writes to the host's ./src, so a make build right after the import
# builds it too.
interface: up
	$(COMPOSE) exec -T $(SERVICE) bash -lc "cd /workspace && vcs import" < interface.repos

# Use after changing the version in interface.repos (or to discard local changes); --force re-checks out
interface-update: up
	$(COMPOSE) exec -T $(SERVICE) bash -lc "cd /workspace && vcs import --force" < interface.repos

build: up
	$(EXEC) bash -lc "colcon build --symlink-install"

# Every Cargo package under src/ (colcon packages are not one cargo workspace, so run each in turn)
MANIFESTS := find src -name Cargo.toml -not -path '*/target/*'

fmt: up
	$(EXEC) bash -lc "$(MANIFESTS) | xargs -r -n1 cargo fmt --manifest-path"

fmt-check: up
	$(EXEC) bash -lc "$(MANIFESTS) | xargs -r -n1 cargo fmt --check --manifest-path"

# Relies on the .cargo/config.toml generated by colcon build to point rclrs / message crates at the underlay
lint: up
	$(EXEC) bash -lc "$(MANIFESTS) | xargs -r -n1 cargo clippy --target-dir build/.clippy --all-targets --manifest-path"

echo: up
	$(EXEC) bash -lc "ros2 topic echo /chatter"

topics: up
	$(EXEC) bash -lc "ros2 topic list"

# build/install/log live in the repo directory (mounted into the container); clean them as the
# container's ros user to avoid permission problems
clean: up
	$(EXEC) bash -lc "find /workspace/build /workspace/install /workspace/log -mindepth 1 -delete"

distclean:
	$(COMPOSE) down -v
