[package]
name = "syncai_driver_manager"
version = "0.1.0"
edition = "2024"

[[bin]]                         # 一個 node 對應一個 [[bin]]，ros2 run 用的就是這個名字
name="syncai_driver_manager"
path = "src/main.rs"

[dependencies]
rclrs="0.8"
ros-env="0.2"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = { level = "warn", priority = -1 }
